import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Arimo } from "next/font/google";
import {  Noto_Sans_JP } from 'next/font/google'
import { Geist, Geist_Mono, Inter, Sen } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const notoJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-jp',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const arimo = Arimo({
  variable: "--font-arimo",
const sen = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${arimo.variable}`}>
      <body className="antialiased">
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${sen.variable} ${notoJP.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
